[package]
name = "ethereum-p2p-handshake"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = "0.7.6"
argh = "0.1.12"
eyre = "0.6.12"
nom = "7.1.3"
rand = "0.8.5"
secp256k1 = { version = "0.29.0", features = [
  "global-context",
  "rand-std",
  "recovery",
] }
tokio = { version = "1.38.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dev-dependencies]
rand_chacha = "0.3.1"
